<?php 
$app->make("config")->set("default_language.folder_code", 'eng');
$app->make("config")->set("default_language.language_code", '1');
$app->make("config")->set("default_language.name", 'English');
$app->make("config")->set("Email.encryption", 'tls');
$app->make("config")->set("Email.host", 'smtp.gmail.com');
$app->make("config")->set("Email.password", 'cdoumqqdfvszsrox');
$app->make("config")->set("Email.port", '465');
$app->make("config")->set("Email.timeout", '30');
$app->make("config")->set("Email.username", 'onlinevidhya27@gmail.com');
$app->make("config")->set("Reading.records_per_pag_action", '5,15,30,50,100,150');
$app->make("config")->set("Reading.records_per_page", '9');
$app->make("config")->set("Site.address", '152/1, First floor Shiprapath, Mansarovar Patel Marg, opp. MRF Tyre Showroom, Jaipur,                                Rajasthan 302020');
$app->make("config")->set("Site.contact_email", 'support@collegesathi.com');
$app->make("config")->set("Site.copyright_text", '&copy; Collegesathi 2024. All Right Reserved.');
$app->make("config")->set("Site.email", 'support@collegesathi.com');
$app->make("config")->set("Site.fcm_key", 'AAAAjXDyLsU:APA91bHlmPe3FrqzI397I4HT5hEYHmXi-BqbzoXsJIaceQKRCE5T-O_L0CqbpLBto77PvN8e1PxveFzP4iQSyh4JowgdTBKtjf5WMS3vqrBud_e4RgNaW2y8BmEGo5P2OsYPMVnC_DTt');
$app->make("config")->set("Site.footer_text", 'Footer About Text Footer About Text Footer About Text');
$app->make("config")->set("Site.for_indian_nationals", '9785- 800- 008');
$app->make("config")->set("Site.for_roreign_nationals", '9785- 800- 008');
$app->make("config")->set("Site.get_in_touch_email", 'support@collegesathi.com');
$app->make("config")->set("Site.get_in_touch_phone", '9785- 800- 008');
$app->make("config")->set("Site.map", 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d113874.30006236058!2d75.70815713116794!3d26.88533996477111!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x396c4adf4c57e281%3A0xce1c63a0cf22e09!2sJaipur%2C%20Rajasthan!5e0!3m2!1sen!2sin!4v1689142255338!5m2!1sen!2sin');
$app->make("config")->set("Site.meta_description", 'Compare Karo, Choose Karo - Elevate Your Career with an Online MBA from Leading Indian Universities. Discover industry-approved programs and make an informed decision with College Sathi.');
$app->make("config")->set("Site.meta_keywords", 'Collegesathi');
$app->make("config")->set("Site.meta_title", 'Choose from the Top Online Universities in India | College Sathi');
$app->make("config")->set("Site.title", 'College Sathi');
$app->make("config")->set("Social.facebook", 'https://www.facebook.com/collegesathi/');
$app->make("config")->set("Social.google_plus", '');
$app->make("config")->set("Social.instagram", 'https://www.instagram.com/collegesathicom/');
$app->make("config")->set("Social.linkedin", '');
$app->make("config")->set("Social.twitter", '');
$app->make("config")->set("Social.youtube", 'http://www.youtube.com/@collegesathicom');
